# Site settings
title: HumansCode
email: ethanzanemiller@gmail.com
description: > 
  a personal blog by ethan miller about topics related to software engineering but sometimes extending into the intersection of technology and society. 
tagline: A personal blog about technology by Ethan Miller
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://humanscodes.com" # the base hostname & protocol for your site
permalink: /:title
twitter_username: ezmiller
github_username:  ezmiller

exclude: [
  Makefile,
  Gemfile,
  Gemfile.lock,
  vendor
]

plugins:
  - jekyll-pandoc

# Build settings
markdown: Pandoc

pandoc:
  extensions:
    - mathjax
    # - normalize
    # - smart
    # - csl: _styles/apa.csl
    # - bibliography: bibliography/references.bib
